node_name       : "Example_Node"
states          : ['INACTIVE', 'UNCONFIGURED', 'INACTIVE', 'ACTIVE', 'INACTIVE', 'UNCONFIGURED', 'ACTIVE', 'UNCONFIGURED']
timeout         : 3
delay           : 1
publications    : ['/Example_Node/chatter']
publishing_hz   : [10]
subscriptions   : ['/noise']
services        : ['/Example_Node/add_two_ints']


